### ISSUE TITLE
Duplicate MANIFEST files

### ISSUE THREAD

**Issue by DimaDDM** [appodeal/appodeal-android-demo#42] opened 2019-11-11 21:38 UTC
Build Appodeal no work with `Gradle 3.5.2` plugin version
With `Gradle 3.5.1` no problem

**Comment by PromanSEW** [comment] 2019-11-12 03:46
Duplicate of #41
Use Gradle plugin 3.4.1

**Closed** 2019-11-12 06:55 UTC
